export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const LOAD_NOTIFICATIONS = "LOAD_NOTIFICATIONS";
export const REMOVE_NOTIFICATIONS = "REMOVE_NOTIFICATIONS";
export const REMOVE_ALL_NOTIFICATIONS = "REMOVE_ALL_NOTIFICATIONS";
