// export const RECEIVE_DECKS = "RECEIVE_DECKS"; // Use Selectors instead
export const ADD_DECK = "ADD_DECK";
export const REMOVE_DECK = "REMOVE_DECK";
export const ADD_CARD = "ADD_CARD";
export const START_QUIZ = "START_QUIZ";
export const ANSWER_QUIZ = "ANSWER_QUIZ";
export const RESET_QUIZ = "RESET_QUIZ";
export const RECEIVE_DECKS = "RECEIVE_DECKS";
export const LOAD_INITIAL_DATA = "LOAD_INITIAL_DATA";
